version: "3.5"

x-environment:
  &default-back-environment
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: taiga
  POSTGRES_HOST: taiga-db
  TAIGA_SECRET_KEY: "taiga-back-secret-key"
  # these rabbitmq settings should be the same as
  # in taiga-rabbitmq and taiga-events services
  RABBITMQ_USER: taiga
  RABBITMQ_PASS: taiga
  CELERY_ENABLED: "False"

x-volumes:
  &default-back-volumes
  # Comment the next two lines to use bind mounts
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # Decomment the next two lines to use bind mounts
  # - ./taigadata/taiga-back/static:/taiga-back/static
  # - ./taigadata/taiga-back/media:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py

services:
  taiga-manage:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    depends_on:
      - taiga-db
    entrypoint: "python manage.py"
    volumes: *default-back-volumes
    networks:
      - taiga
